### ISSUE TITLE
Cards with # don't work in set lists

### ISSUE THREAD

**Issue by BritishCynic** [chinhodado/ygodb#2]
Hello

Just noticed that your card sets don't like the Wiki's use of "#" in card names when it comes to set card lists. How much of a problem is it to fix?

**Comment by chinhodado** [comment]
Sorry I don't think I quite understand this. Can you give me an example?

**Comment by chinhodado** [comment]
I see what you mean now. Cards like [M-Warrior #2](http://yugioh.wikia.com/wiki/M-Warrior_2) display correctly in the main card list but not in the set card list. Interesting. I'll find out why.

**Comment by BritishCynic** [comment]
I think it happens because you use the link text over the actual URL in the link to retrieve the card information. Same thing also happens with "Return (card)", and I'm sure a few others.

**Comment by chinhodado** [comment]
You're right. I use the title of the article for the card name, and this is not correct because in many cases the title is not the correct name, sometimes because wikia doesn't allow some characters in the page title (e.g. # [ ] { } |), sometimes because we need to distinguish different things with the same name.

**Comment by chinhodado** [comment]
Here is the list of cards whose article name does not match the card name:

![image](https://cloud.githubusercontent.com/assets/1388219/23880955/6c79bcd0-082d-11e7-8902-de8a722ea8ff.png)

**Comment by chinhodado** [comment]
Fixed in 2.0.2
